name: 🐞 Bug Report
description: Report a bug or unexpected behavior in EventManage
labels: [bug]

body:
  - type: textarea
    id: description
    attributes:
      label: "🐞 Bug Description"
      description: "Briefly describe the issue or bug you're encountering."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "📋 Steps to Reproduce"
      description: "Provide clear and detailed steps to reproduce the issue."
      placeholder: |
        1. Setup EventManager with default config
        2. Call logger.info("...")
        3. Observe issue...
    validations:
      required: true

  - type: textarea
    id: behavior
    attributes:
      label: "More description on the behavior"
      description: "Describe clearly what happened."
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: "🔧 Environment"
      description: "Include details about your environment (Java version, OS, EventManager version, etc.)"
      placeholder: |
        - EventManager version: 1.x.x
        - Java version: OpenJDK 17
        - OS: Windows/Linux/macOS
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: "📝 Additional Context (Optional)"
      description: "Add any additional context or screenshots related to the issue."
    validations:
      required: false